[build]
    functions = 'functions'
    publish = 'public'

[dev]
    command = 'npm run develop'
    publish = 'public'
    port = 8888
    targetPort = 8000

[[redirects]]
    from = 'api/*'
    to = '.netlify/functions/:splat'
    status = 200
